---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: health-check
  namespace: observability
spec:
  runInterval: 1m
  timeout: 5m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
          - name: KH_REPORTING_URL ##Kuberhealthy endpoint
            value: "kuberhealthy.kuberhealthy.svc"
          - name: NAMESPACE
            value: "services"
          - name: "PROMETHEUS_ENDPOINT"
            value: "http://nopo11y-stack-kube-prometh-prometheus.observability.svc:9090/prometheus"
        image: ghcr.io/znsio/nopo11y/system_health_check:2.1
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true