{{- if and .Values.gateway.tls.enabled (or (ne (int .Values.gateway.portNumber) 443) (ne .Values.gateway.protocol "HTTPS") (ne .Values.gateway.portName "https"))}}
{{fail "When TLS is enabled then port should be 443, protocol should be HTTPS and port name should be https"}}
{{- end }}
{{- if and (not .Values.gateway.tls.enabled) (or (ne (int .Values.gateway.portNumber)  80) (ne .Values.gateway.protocol "HTTP") (ne .Values.gateway.portName "http"))}}
{{fail "When TLS is disabled then port should be 80, protocol should be HTTP and port name should be http"}}
{{- end }}
{{- if .Values.gateway.name }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    {{- toYaml .Values.gateway.gatewaySelector |nindent 4 }}
  servers:
  - port:
      number: {{ .Values.gateway.portNumber }}
      name: {{ .Values.gateway.portName }}
      protocol: {{ .Values.gateway.protocol }}
    hosts:
    {{- range .Values.gateway.hosts }}
    - {{ . |quote }}
    {{- end }}
    {{- if .Values.gateway.tls.enabled }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.gateway.name }}-{{ .Values.gateway.namespace }}-tls-secret
    {{- end }}
{{- end }}
