{{- if hasKey .Values.o11y.specmatic.stub "pat" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-specmatic-stub-repo-checkout-secret
  namespace: {{ include "npl.svc.namespace" . }}
stringData:
  pat: {{ .Values.o11y.specmatic.stub.pat | quote }}
{{- end }}