apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nopo11yconfigs.znsio.nopo11y.com
spec:
  group: znsio.nopo11y.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum:
                - znsio.nopo11y.com/v1alpha
            kind:
              type: string
              enum:
                - Nopo11yConfig
            metadata:
              type: object
            spec:
              type: object
              properties:
                defaults:
                  type: object
                  properties:
                    slo:
                      type: object
                      properties:
                        availability:
                          type: number
                        latency:
                          type: number
                    alertThresholds:
                      type: object
                      properties:
                        latencyMs:
                          type: integer
                        errorRate4xx:
                          type: number
                        errorRate5xx:
                          type: number
                services:
                  type: array
                  items:
                    type: object
                    required:
                      - namespace
                      - serviceName
                    properties:
                      namespace:
                        type: string
                      serviceName:
                        type: string
                      deploymentName:
                        type: string
                      clusterName:
                        type: string
                      slo:
                        type: object
                        properties:
                          availability:
                            type: number
                          latency:
                            type: number
                      alertThresholds:
                        type: object
                        properties:
                          latencyMs:
                            type: integer
                          errorRate4xx:
                            type: number
                          errorRate5xx:
                            type: number
  scope: Namespaced
  names:
    plural: nopo11yconfigs
    singular: nopo11yconfig
    kind: Nopo11yConfig
    shortNames:
      - npc
