apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tracing
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 16686
    # Note: Change port name if you add '--query.grpc.tls.enabled=true'
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: metrics
      port: 14269
      protocol: TCP
      targetPort: 14269
  selector:
    app: jaeger
---
# Jaeger implements the Zipkin API. To support swapping out the tracing backend, we use a Service named Zipkin.
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: {{ .Release.Name }}-zipkin
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9411
      targetPort: 9411
      name: http-query
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
  - name: jaeger-collector-http
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: jaeger-collector-grpc
    port: 14250
    targetPort: 14250
    protocol: TCP
  - port: 9411
    targetPort: 9411
    name: http-zipkin
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: jaeger-collector-oltp-http
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: jaeger-collector-oltp-grpc
  selector:
    app: jaeger