helmReleaseNamespace: observability
jaeger:
  image: docker.io/jaegertracing/all-in-one:1.35
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  pathPrefix: /jaeger
  persistence:
    enabled: false
    accessModes:
    - ReadWriteOnce
    storageClassName: "default"
    size: 8Gi
  tracesTTL: "168h"
  serviceMonitor:
    enabled: false
    labels: {}
      # app: "jaeger"
      # env: "Dev"