{{- if and (.Values.nopo11y_ingress.enabled) (eq .Values.nopo11y_ingress.type "istio") }}
{{- if .Values.nopo11y_ingress.tls.enabled }}
{{- if gt (len (include "nopo11y.services" . |fromJsonArray)) 0 }}
{{- if or (not .Values.nopo11y_ingress.tls.tlsKey) (not .Values.nopo11y_ingress.tls.tlsCert) }}
{{- fail "If tls is enaled for nopo11y_ingress then tls.tlsKey and tls.tlsCert can not be empyt" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-tls-secret
  namespace: {{ .Values.nopo11y_ingress.istioNamespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.nopo11y_ingress.tls.tlsCert  }}
  tls.key: |
    {{ .Values.nopo11y_ingress.tls.tlsKey }}
{{- end }}
{{- end }}
{{- end }}