{{- if (index .Values "kiali-server" "oidc_secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
data:
  oidc-secret: {{ index .Values "kiali-server" "oidc_secret" }}
{{- end }}