apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry-webhook.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "sentry-webhook.fullname" . }}-webhook
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443