apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry-webhook.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentry-webhook.fullname" . }}-webhook
  template:
    metadata:
      labels:
        app: {{ include "sentry-webhook.fullname" . }}-webhook
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: sentry-webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9443
              name: https
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tls-secret
              mountPath: /certs
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            defaultMode: 420
            secretName: {{ include "sentry-webhook.fullname" . }}-webhook-certs