apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "sentry-webhook.fullname" . }}-webhook-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name:  {{ include "sentry-webhook.fullname" . }}-webhook-create
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webhook-create
          image: "{{ .Values.certgen.image.repository }}:{{ .Values.certgen.image.tag }}"
          imagePullPolicy: "{{ .Values.certgen.image.pullPolicy }}"
          args:
            - create
            - --host="{{ include "sentry-webhook.fullname" . }}-webhook,{{ include "sentry-webhook.fullname" . }}-webhook.{{ .Release.Namespace }}.svc,{{ include "sentry-webhook.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local"
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "sentry-webhook.fullname" . }}-webhook-certs
          {{- if .Values.certgen.resources }}
          resources:
          {{- toYaml .Values.certgen.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "sentry-webhook.fullname" . }}-webhook