apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.api.service.nameGenerated.readable }}-hpa
  namespace: {{ include "npl.svc.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.api.service.nameGenerated.readable }}
  minReplicas: {{ .Values.api.pod.hpa.replicas.min }}
  maxReplicas: {{ .Values.api.pod.hpa.replicas.max }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Values.api.service.nameGenerated.readable }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.pod.hpa.averageUtilizationPercentage.cpu }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ .Values.api.service.nameGenerated.readable }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.pod.hpa.averageUtilizationPercentage.memory }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.api.pod.hpa.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.api.pod.hpa.scaleUp.pods.count }}
        periodSeconds: {{ .Values.api.pod.hpa.scaleUp.pods.periodSeconds }}
      - type: Percent
        value: {{ .Values.api.pod.hpa.scaleUp.percent.value }}
        periodSeconds: {{ .Values.api.pod.hpa.scaleUp.percent.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.api.pod.hpa.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.api.pod.hpa.scaleDown.pods.count }}
        periodSeconds: {{ .Values.api.pod.hpa.scaleDown.pods.periodSeconds }}
      - type: Percent
        value: {{ .Values.api.pod.hpa.scaleDown.percent.value }}
        periodSeconds: {{ .Values.api.pod.hpa.scaleDown.percent.periodSeconds }}


