{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- if hasKey .Values.api.container.metrics "port" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "npl.svc.metricsName" . }}
  labels:
    app: {{ .Values.api.service.nameGenerated.readable }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.service.nameGenerated.readable }}
  endpoints:
  - port: {{ include "npl.svc.metricsPortRef" . }}
    interval: {{ .Values.api.container.metrics.interval }}
---
{{- end }}
{{- end }}