apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "npl.svc.name" . }}-vs
spec:
  gateways:
  {{- if not (hasKey .Values.api.service "gateways") }}
  - {{ include "npl.svc.name" . }}-gw
  {{- else }}
    {{- toYaml .Values.api.service.gateways | nindent 2 }}
  {{- end }}
  hosts:
  - '*'
  http:
  - name: {{ .Values.api.service.nameGenerated.readable }}-default-route
    match:
    - uri:
        prefix: {{ printf "/%s/" (.Values.api.service.name) | quote }}
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ .Values.api.service.nameGenerated.readable }}.{{ include "npl.svc.namespace" . }}.svc.cluster.local
        port:
          number: {{ .Values.api.service.port }}
