name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'tools/nopo11y-operator/**'
      - '!tools/nopo11y-operator/*.md'

env:
  IMAGE_REPO: ghcr.io/znsio/nopo11y/nopo11y-operator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: |
          cd ./tools/nopo11y-operator/
          docker build . -t $IMAGE_REPO:${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.IMAGE_REPO }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker Image
        run: docker push $IMAGE_REPO:${{ github.sha }}
